"""
build_integration.py — P2: Build-system hook + compiler wrapper.

Provides:
1.  compile_commands.json parser (cmake / bear output) — discovers all files
    that are actually compiled, with their compile flags.
2.  Compiler wrapper generator — creates shell scripts `overflowguard-cc`
    and `overflowguard-c++` that transparently add ASAN/UBSAN flags and
    emit a findings report after each translation unit.
3.  BuildIntegrator — high-level class used by main.py.

Exported API:
    CompileCommand           — dataclass for one file's compile entry
    BuildIntegrator          — scan_compile_commands(path)
                             — generate_wrappers(output_dir)
                             — get_files() → List[str]
"""

import json
import os
import shutil
import stat
from dataclasses import dataclass, field
from typing import List, Optional


@dataclass
class CompileCommand:
    file:      str
    directory: str
    command:   str
    flags:     List[str] = field(default_factory=list)

    @property
    def abs_path(self) -> str:
        if os.path.isabs(self.file):
            return self.file
        return os.path.normpath(os.path.join(self.directory, self.file))


def _parse_compile_commands(path: str) -> List[CompileCommand]:
    """
    Parse a compile_commands.json file (generated by CMake or Bear).
    Returns a list of CompileCommand instances for C/C++ translation units.
    """
    try:
        with open(path, "r", errors="ignore") as fh:
            data = json.load(fh)
    except (OSError, json.JSONDecodeError):
        return []

    cmds: List[CompileCommand] = []
    c_extensions = {".c", ".cpp", ".cc", ".cxx"}
    for entry in data:
        if not isinstance(entry, dict):
            continue
        fil = entry.get("file", "")
        if os.path.splitext(fil)[1].lower() not in c_extensions:
            continue
        cmd_str  = entry.get("command", entry.get("arguments", ""))
        if isinstance(cmd_str, list):
            cmd_str = " ".join(cmd_str)
        flags    = [
            t for t in cmd_str.split()
            if t.startswith("-") and t not in ("-c", "-o")
        ]
        cc = CompileCommand(
            file=fil,
            directory=entry.get("directory", os.getcwd()),
            command=cmd_str,
            flags=flags,
        )
        cmds.append(cc)
    return cmds


# ── Compiler wrapper templates ─────────────────────────────────────────────────
_WRAPPER_TEMPLATE = """\
#!/usr/bin/env bash
# OverflowGuard compiler wrapper for {compiler_name}
# Transparently adds ASAN/UBSAN flags and invokes OverflowGuard analysis.
set -euo pipefail

# Locate real compiler
REAL="{real_compiler}"
if [ ! -x "$REAL" ]; then
    REAL=$(command -v {compiler_name} 2>/dev/null || echo "")
fi
if [ -z "$REAL" ]; then
    echo "OverflowGuard wrapper: cannot find {compiler_name}" >&2
    exit 1
fi

# Build with sanitisers
extra="-g -fsanitize=address,undefined -fno-omit-frame-pointer"
"$REAL" $extra "$@"

# Determine the source file (first non-flag .c/.cpp arg)
src=""
for arg in "$@"; do
    case "$arg" in
        *.c|*.cpp|*.cc|*.cxx) src="$arg"; break ;;
    esac
done

# Run OverflowGuard on the source file in the background
if [ -n "$src" ] && command -v python3 &>/dev/null; then
    python3 -m overflowguard.main "$src" --quiet >> "${{OVERFLOWGUARD_LOG:-overflowguard.log}}" 2>&1 &
fi
"""

_ENTRY_POINT_TEMPLATE = """\
#!/usr/bin/env python3
\"\"\"
overflowguard-scan — CLI entry point for build-integration scanning.
Reads compile_commands.json and runs OverflowGuard on every discovered file.
\"\"\"
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
from build_integration import BuildIntegrator

if __name__ == "__main__":
    import argparse
    p = argparse.ArgumentParser(description="OverflowGuard build scanner")
    p.add_argument("compile_commands", nargs="?",
                   default="compile_commands.json",
                   help="Path to compile_commands.json")
    p.add_argument("--output-wrappers", metavar="DIR",
                   help="Directory to write compiler wrapper scripts")
    args = p.parse_args()

    bi = BuildIntegrator()
    if os.path.isfile(args.compile_commands):
        bi.scan_compile_commands(args.compile_commands)
        files = bi.get_files()
        print(f"[BuildIntegrator] Discovered {len(files)} source files")
        for f in files:
            print(f"  {f}")
    else:
        print(f"[BuildIntegrator] {args.compile_commands} not found", file=sys.stderr)

    if args.output_wrappers:
        paths = bi.generate_wrappers(args.output_wrappers)
        for path in paths:
            print(f"[BuildIntegrator] Wrapper written: {path}")
"""


# ── BuildIntegrator ───────────────────────────────────────────────────────────
class BuildIntegrator:
    """
    High-level interface for build-system integration.

    Usage:
        bi = BuildIntegrator()
        bi.scan_compile_commands("build/compile_commands.json")
        files = bi.get_files()   # → list of absolute .c/.cpp paths
        bi.generate_wrappers("/usr/local/bin")
    """

    def __init__(self):
        self._commands: List[CompileCommand] = []

    def scan_compile_commands(self, path: str) -> List[CompileCommand]:
        """
        Parse compile_commands.json at *path* and store discovered files.
        Returns the list of CompileCommand objects.
        """
        self._commands = _parse_compile_commands(path)
        return self._commands

    def get_files(self) -> List[str]:
        """Return deduplicated absolute paths of all discovered source files."""
        seen = set()
        result = []
        for cmd in self._commands:
            p = cmd.abs_path
            if p not in seen and os.path.isfile(p):
                seen.add(p)
                result.append(p)
        return result

    def get_flags_for(self, file_path: str) -> List[str]:
        """Return the compile flags for a specific file, or []."""
        abs_p = os.path.abspath(file_path)
        for cmd in self._commands:
            if cmd.abs_path == abs_p:
                return cmd.flags
        return []

    def generate_wrappers(self, output_dir: str) -> List[str]:
        """
        Write `overflowguard-cc` and `overflowguard-c++` wrapper shell scripts
        to *output_dir*.  Returns list of created file paths.
        """
        os.makedirs(output_dir, exist_ok=True)
        created: List[str] = []

        for name, real in [("gcc", "gcc"), ("cc", "gcc"),
                            ("g++", "g++"), ("c++", "g++"),
                            ("clang", "clang"), ("clang++", "clang++")]:
            wrapper_name = f"overflowguard-{name}"
            real_path    = shutil.which(real) or real
            content = _WRAPPER_TEMPLATE.format(
                compiler_name=name,
                real_compiler=real_path,
            )
            out_path = os.path.join(output_dir, wrapper_name)
            with open(out_path, "w") as fh:
                fh.write(content)
            # Make executable
            cur = stat.S_IMODE(os.stat(out_path).st_mode)
            os.chmod(out_path, cur | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
            created.append(out_path)

        # Also write the CLI entry-point scanner
        scanner_path = os.path.join(output_dir, "overflowguard-scan")
        with open(scanner_path, "w") as fh:
            fh.write(_ENTRY_POINT_TEMPLATE)
        cur = stat.S_IMODE(os.stat(scanner_path).st_mode)
        os.chmod(scanner_path, cur | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        created.append(scanner_path)

        return created

    @staticmethod
    def cmake_generate_compile_commands(build_dir: str) -> bool:
        """
        Run `cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON .` in *build_dir*.
        Returns True on success.
        """
        import subprocess
        result = subprocess.run(
            ["cmake", "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON", "."],
            cwd=build_dir,
            capture_output=True,
            text=True,
        )
        return result.returncode == 0

    @staticmethod
    def bear_intercept(build_command: List[str], output_dir: str) -> bool:
        """
        Use `bear` to intercept a build command and produce compile_commands.json.
        Returns True if bear is available and the command succeeded.
        """
        import subprocess
        if not shutil.which("bear"):
            return False
        cmd = ["bear", "--output",
               os.path.join(output_dir, "compile_commands.json"), "--"] + build_command
        result = subprocess.run(cmd, cwd=output_dir, capture_output=True, text=True)
        return result.returncode == 0
