"""
false_positive_filter.py — Context‑aware false‑positive reduction for
OverflowGuard v9.0

Reduces false positives by applying multiple contextual checks:

1. **Test code detection** — findings inside test functions / test files
   are downgraded to LOW / suppressed.
2. **Dead code elimination** — findings inside ``if (0)`` / ``if False``
   or ``#if 0`` blocks are suppressed.
3. **Sanitizer guard verification** — if a sanitizer *dominates* the sink
   in the CFG, the finding is suppressed (uses :mod:`cfg_builder` dominator
   analysis, not a crude line‑distance heuristic).
4. **Duplicate / subsumption** — multiple findings from different analyzers
   for the same root cause are merged.
5. **Confidence scoring** — each surviving finding gets a confidence score
   based on:
     ▪ whether the AST / CFG / symbolic engine confirmed it
     ▪ whether the finding is in test / generated code
     ▪ whether there's a partial guard (but not dominating)

Replaces the simple ``ml_filter.py`` RandomForest and the ±10‑line
heuristic in old ``dataflow.py``.
"""

from __future__ import annotations

import os
import re
from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Set, Tuple

from tree_sitter_engine import (
    ASTQueries,
    TSNode,
    TS_AVAILABLE,
    language_for_file,
    parse_file,
)
from cfg_builder import CFG, build_cfgs

# ---------------------------------------------------------------------------
# Generic finding interface
# ---------------------------------------------------------------------------

@dataclass
class Finding:
    """Normalised finding that any analyzer can produce."""
    issue_type: str
    line: int
    snippet: str
    note: str
    confidence: str   # "High" | "Medium" | "Low"
    stage: str = ""   # which analyzer produced it
    source_line: int = 0
    sink_line: int = 0
    file_path: str = ""
    _suppressed: bool = False
    _reason: str = ""


# ---------------------------------------------------------------------------
# Detection helpers
# ---------------------------------------------------------------------------

# Filename patterns that indicate test code
_TEST_FILE_PATTERNS = re.compile(
    r"(?:^|/)(?:tests?|specs?|__tests__|test_|_test\b|spec_|_spec\b)"
    r"|(?:^|/)conftest\.py$"
    r"|(?:_test|_spec|Test|Spec)\.[a-z]+$",
    re.IGNORECASE,
)

# Function name patterns that indicate test code
_TEST_FUNC_PATTERNS = re.compile(
    r"^(?:test_|spec_|it_|describe_|should_|setUp|tearDown|before|after|"
    r"Test[A-Z]|Spec[A-Z]|test[A-Z])",
)

# Patterns that indicate generated / auto‑generated code
_GENERATED_PATTERNS = re.compile(
    r"(?:auto[-_]?generated|machine[-_]?generated|DO NOT (?:EDIT|MODIFY)"
    r"|generated by|code[-_]?gen|protobuf|thrift)",
    re.IGNORECASE,
)


def is_test_file(file_path: str) -> bool:
    """Return True if *file_path* looks like a test file."""
    return bool(_TEST_FILE_PATTERNS.search(file_path))


def is_test_function(func_name: str) -> bool:
    """Return True if *func_name* looks like a test function."""
    return bool(_TEST_FUNC_PATTERNS.search(func_name))


def is_generated_file(file_path: str, first_lines: str = "") -> bool:
    """Return True if the file appears to be auto‑generated."""
    if _GENERATED_PATTERNS.search(os.path.basename(file_path)):
        return True
    return bool(_GENERATED_PATTERNS.search(first_lines[:500]))


def _is_dead_code_block(node: TSNode) -> bool:
    """
    Check if *node* is inside a dead‑code block such as ``if (0) { ... }``
    or ``if False:`` in Python.
    """
    for anc in node.ancestors():
        if anc.type in ("if_statement", "if_expression"):
            cond = anc.child_by_field("condition")
            if cond:
                text = cond.text.strip()
                if text in ("0", "false", "False", "nil", "null", "0L"):
                    return True
    return False


# ---------------------------------------------------------------------------
# Main filter
# ---------------------------------------------------------------------------


class FalsePositiveFilter:
    """
    Applies multiple heuristics and analyses to suppress or downgrade findings
    that are likely false positives.
    """

    def __init__(self, file_path: str = ""):
        self.file_path = file_path
        self._root: Optional[TSNode] = None
        self._queries: Optional[ASTQueries] = None
        self._cfgs: Optional[List[CFG]] = None
        self._source_lines: List[str] = []
        self._lang: Optional[str] = None
        self._parsed = False

    def _ensure_parsed(self) -> None:
        if self._parsed:
            return
        self._parsed = True
        if not self.file_path or not TS_AVAILABLE:
            return
        self._lang = language_for_file(self.file_path)
        if self._lang is None:
            return
        self._root, self._queries = parse_file(self.file_path)
        if self._root:
            self._cfgs = build_cfgs(self._root, self._lang)
        try:
            with open(self.file_path, "r", errors="replace") as fh:
                self._source_lines = fh.readlines()
        except Exception:
            pass

    # ==== public API ======================================================

    def filter(self, findings: List[Finding]) -> List[Finding]:
        """
        Filter a list of findings, returning only those that survive.
        Suppressed findings have ``_suppressed = True`` and ``_reason`` set.
        """
        self._ensure_parsed()

        surviving: List[Finding] = []
        seen: Set[Tuple[str, int]] = set()  # (issue_type, line) for dedup

        for f in findings:
            # 1. Dedup
            key = (f.issue_type, f.line)
            if key in seen:
                f._suppressed = True
                f._reason = "duplicate"
                continue
            seen.add(key)

            # 2. Test code
            if is_test_file(f.file_path or self.file_path):
                f.confidence = "Low"
                f.note += " [in test file — downgraded]"

            # 3. Generated code
            first_lines = "".join(self._source_lines[:5]) if self._source_lines else ""
            if is_generated_file(f.file_path or self.file_path, first_lines):
                f._suppressed = True
                f._reason = "generated_code"
                continue

            # 4. Dead code
            if self._root and self._is_in_dead_code(f.line):
                f._suppressed = True
                f._reason = "dead_code"
                continue

            # 5. Sanitizer domination (CFG-based)
            if self._cfgs and self._is_guarded_by_sanitizer(f):
                f._suppressed = True
                f._reason = "sanitizer_dominates"
                continue

            # 6. Test function name
            if self._root and self._queries:
                func = self._enclosing_function(f.line)
                if func and is_test_function(func):
                    f.confidence = "Low"
                    f.note += f" [in test function '{func}' — downgraded]"

            # 7. Confidence adjustment
            f.confidence = self._adjust_confidence(f)

            surviving.append(f)

        return surviving

    # ==== internals =======================================================

    def _is_in_dead_code(self, line: int) -> bool:
        """Check if *line* falls inside a dead‑code block in the AST."""
        if not self._root:
            return False
        for node in self._root.walk():
            if node.start_line <= line <= node.end_line:
                if _is_dead_code_block(node):
                    return True
        return False

    def _is_guarded_by_sanitizer(self, f: Finding) -> bool:
        """
        Check if the finding's sink line is dominated by a sanitizer call
        in the same function's CFG.
        """
        if not self._cfgs or not self._queries:
            return False

        for cfg in self._cfgs:
            # Find block containing the finding's line
            sink_bid: Optional[int] = None
            for blk in cfg.all_blocks():
                for stmt in blk.stmts:
                    if stmt.line == f.line:
                        sink_bid = blk.id
                        break
                if sink_bid is not None:
                    break

            if sink_bid is None:
                continue

            # Find blocks containing sanitizer calls
            for blk in cfg.all_blocks():
                for stmt in blk.stmts:
                    if stmt.kind == "call":
                        for call_node in stmt.node.walk():
                            call_types = self._queries._CALL_TYPES.get(
                                self._lang or "", set()
                            )
                            if call_node.type in call_types:
                                if self._queries.is_sanitizer_call(call_node):
                                    if cfg.dominates(blk.id, sink_bid):
                                        return True

        return False

    def _enclosing_function(self, line: int) -> Optional[str]:
        """Return the name of the function containing *line*, or None."""
        if not self._root or not self._queries:
            return None
        for func in self._queries.find_functions(self._root):
            if func.start_line <= line <= func.end_line:
                return self._queries.function_name(func)
        return None

    def _adjust_confidence(self, f: Finding) -> str:
        """Adjust confidence based on multiple signals."""
        score = {"High": 3, "Medium": 2, "Low": 1}.get(f.confidence, 2)

        # Boost if we have taint path evidence
        if f.source_line and f.sink_line and f.source_line != f.sink_line:
            score = min(score + 1, 3)

        # Reduce if the snippet is very short (might be a misparse)
        if len(f.snippet.strip()) < 5:
            score = max(score - 1, 1)

        return {3: "High", 2: "Medium", 1: "Low"}.get(score, "Medium")
